apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.api.componentName }}-secrets
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: {{ .Values.api.componentName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  google-client-secret: {{ .Values.googleClientSecret | b64enc | quote }}
  facebook-client-secret: {{ .Values.facebookClientSecret | b64enc | quote }}
  github-client-secret: {{ .Values.githubClientSecret | b64enc | quote }}

  gcp-private-key: {{ .Values.gcpPrivateKey | b64enc | quote }}
