apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.api.componentName }}-deployment
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: {{ .Values.api.componentName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "name" . }}
      app.kubernetes.io/component: {{ .Values.api.componentName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
        app.kubernetes.io/name: {{ template "name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: {{ .Values.api.componentName }}
    spec:
      containers:
        - name: {{ .Values.api.componentName }}
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          ports:
            - containerPort: {{ .Values.api.serverPort }}

          livenessProbe:
            httpGet:
              path: {{ .Values.api.healthinessProbePath }}
              port: {{ .Values.api.serverPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: {{ .Values.api.readinessProbePath }}
              port: {{ .Values.api.serverPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

      volumes:
        - name: {{ .Values.api.componentName }}-secrets
          secret:
            secretName: {{ .Release.Name }}-{{ .Values.api.componentName }}-secrets
