apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: {{ .Values.domainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.web.componentName }}-service
          servicePort: 80
  - host: api.{{ .Values.domainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.api.componentName }}-service
          servicePort: 80
