apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.web.componentName }}-service
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: {{ .Values.web.componentName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: {{ .Values.web.componentName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.web.serverPort }}
